- name: Create database (http://docs.ansible.com/ansible/postgresql_db_module.html)
  become: yes
  become_user: postgres
  postgresql_db:
    name=testdb
    encoding='UTF-8'
    lc_collate='ja_JP.UTF-8'
    lc_ctype='ja_JP.UTF-8'
    template='template0'
